# Generated by Django 3.0.2 on 2023-03-01 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タスク名')),
                ('startdate', models.IntegerField(blank=True, max_length=255, verbose_name='開始日')),
                ('deadline', models.IntegerField(blank=True, max_length=255, verbose_name='期限')),
                ('estimate', models.IntegerField(blank=True, max_length=255, verbose_name='見積もり(日)')),
                ('completion', models.IntegerField(blank=True, max_length=255, verbose_name='完了日')),
                ('status', models.IntegerField(default=0, max_length=255, verbose_name='ステータス')),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='完了日', to='todo.ToDo', verbose_name='タスク名')),
            ],
        ),
    ]
